home_store
PandaRec/DesignFromFigma pull request #1
Opened 2021-04-13 18:31 UTC by PandaRec

2021-04-13 21:01 UTC, sbalakin requested changes

2021-04-13 21:01 UTC, sbalakin commented on app/src/main/java/com/example/designfromfigma2/adapters/BestSellerAdapter.kt
> +    var context : Context? = null
Контекст тут лишний

2021-04-13 21:01 UTC, sbalakin commented on app/src/main/java/com/example/designfromfigma2/adapters/BestSellerAdapter.kt
> +    var onLikeClickListener: OnLikeClickListener?=null
Так тоже не стоит делать

2021-04-13 21:01 UTC, sbalakin commented on app/src/main/java/com/example/designfromfigma2/adapters/BestSellerAdapter.kt
> +        holder.imageViewMain.setImageDrawable(context?.let { ResourcesCompat.getDrawable(it.resources,current.imageId,null) })
Это все нужно вынести во BestSellerViewHolder. Нарушение логики, управляем классом извне

2021-04-13 21:01 UTC, sbalakin commented on app/src/main/java/com/example/designfromfigma2/adapters/CategoryAdapter.kt
> +        holder.imageViewSub.setImageDrawable(context?.let { ResourcesCompat.getDrawable(it.resources,current.imageId,null) })
Аналогично

2021-04-13 21:01 UTC, sbalakin commented on app/src/main/java/com/example/designfromfigma2/ui/home/HomeFragment.kt
> +        adapterBestSeller.onLikeClickListener = object : BestSellerAdapter.OnLikeClickListener{
Похоже, что пытался сделать нажатия, но в задании этого не было. Не стоит делать, чего не просит заказчик

2021-04-15 04:22 UTC, AndrewBlack-hub commented on app/src/main/java/com/example/designfromfigma2/ui/home/HomeViewModel.kt
> +        item = BestSellerMenu("\$300","\$400","Motorola One Edge",R.drawable.motorola,false)
На сколько я понимаю, модели телефонов должны быть вынесены в ресурсы и, соответственно, добавляться в код оттуда

2021-04-15 04:22 UTC, AndrewBlack-hub commented on app/src/main/java/com/example/designfromfigma2/ui/home/HomeViewModel.kt
> +        item = CategoryItemMenu(R.drawable.ic_books, "Books",false)
заголовки категорий не вынесены в ресурсы

2021-04-15 04:22 UTC, AndrewBlack-hub commented on app/src/main/java/com/example/designfromfigma2/adapters/HotSaleAdapter.kt
> +            imageViewMain.setImageDrawable(getDrawable(itemView.context.resources,hotSaleItemImgId,null))
Можно обойтись без контекста. Т.к. для андроида передавать его трудозатратно, то стоит его исключить и заменить код более простым: 
private val imgCategory: ImageView = view.iv_category_ic_grey
fun insertToUI(current: YourModel) {
    imgCategory.setImageResource(current.img)
}

2021-04-15 04:22 UTC, AndrewBlack-hub commented on app/src/main/java/com/example/designfromfigma2/adapters/CategoryAdapter.kt
> +                )
Тоже можно обойтись imageViewSub.setImageResource(Int)

2021-04-15 04:22 UTC, AndrewBlack-hub commented on app/src/main/java/com/example/designfromfigma2/adapters/BestSellerAdapter.kt
> +            textViewOldPrice.text = bestSeller.oldPrice
когда вынесешь эти поля в ресурсы и придется брать их оттуда, то будешь получать Int и нужно будет изменить способ инициализации. Например: textViewTitle.setText(R.string.fullTitle)

2021-04-30 22:19 UTC, merged