Splash
PandaRec/DesignFromFigma pull request #2
Opened 2021-04-21 16:30 UTC by PandaRec

Start Page

2021-04-22 13:48 UTC, sbalakin requested changes

2021-04-22 13:48 UTC, sbalakin commented on app/src/main/java/com/example/designfromfigma2/MainActivity.kt
> +        val fragmentManager = supportFragmentManager
А почему не через NC сделал навигацию?

2021-04-22 13:48 UTC, sbalakin commented on app/src/main/java/com/example/designfromfigma2/adapters/BestSellerAdapter.kt
> +    var onLikeClickListener: OnLikeClickListener?=null
Договаривались, что ты это уберешь

2021-04-22 13:48 UTC, sbalakin commented on app/src/main/java/com/example/designfromfigma2/adapters/BestSellerAdapter.kt
> +        holder.itemView.setOnClickListener { onLikeClickListener?.onLikeClick(position) }
Нарушение инкапсуляции

2021-04-22 13:48 UTC, sbalakin commented on app/src/main/java/com/example/designfromfigma2/adapters/CategoryAdapter.kt
> +        holder.itemView.setOnClickListener { onCategoryClickListener?.onCategoryClick(position) }
аналогично

2021-04-22 13:48 UTC, sbalakin commented on app/src/main/java/com/example/designfromfigma2/ui/home/HomeFragment.kt
> +        val spinner = root.spinnerGeo
в отдельные методы эти строчки кода

2021-04-22 13:48 UTC, sbalakin commented on app/src/main/java/com/example/designfromfigma2/ui/home/HomeFragment.kt
> +
и эти

2021-04-22 13:48 UTC, sbalakin commented on app/src/main/res/layout/fragment_home.xml
> +        android:queryHint="Search"
в ресурсы

2021-04-22 13:48 UTC, sbalakin commented on app/src/main/res/layout/fragment_home.xml
> +    <ImageView
надо бы разбить файл на несколько

2021-04-22 14:02 UTC, PandaRec commented on app/src/main/java/com/example/designfromfigma2/adapters/BestSellerAdapter.kt
> +    var onLikeClickListener: OnLikeClickListener?=null
думал на будущее не делать лишнего. понял, уберу

2021-04-23 09:32 UTC, PandaRec commented on app/src/main/java/com/example/designfromfigma2/MainActivity.kt
> +        val fragmentManager = supportFragmentManager
почему то снова старый файл
посмотрел ветку, у меня видно другое. Не могу понять почему (смотрел на гитхабе)
навигация сделана в данном файле след. образом:
val fragmentManager = supportFragmentManager
        val fragmentTransaction = fragmentManager.beginTransaction()

        val homeFragment = HomeFragment()
        fragmentTransaction.add(R.id.nav_host_fragment,homeFragment).commit()

2021-04-23 09:37 UTC, PandaRec commented on app/src/main/java/com/example/designfromfigma2/adapters/BestSellerAdapter.kt
> +    var onLikeClickListener: OnLikeClickListener?=null
убрал

2021-04-23 09:39 UTC, PandaRec commented on app/src/main/java/com/example/designfromfigma2/adapters/BestSellerAdapter.kt
> +        holder.itemView.setOnClickListener { onLikeClickListener?.onLikeClick(position) }
убрал likeListener

2021-04-23 09:40 UTC, PandaRec commented on app/src/main/java/com/example/designfromfigma2/adapters/CategoryAdapter.kt
> +        holder.itemView.setOnClickListener { onCategoryClickListener?.onCategoryClick(position) }
сделал

2021-04-23 09:42 UTC, PandaRec commented on app/src/main/java/com/example/designfromfigma2/ui/home/HomeFragment.kt
> +        val spinner = root.spinnerGeo
26, 27, 28 строк нет в файлах давно
значит ничего не менять?

2021-04-23 09:58 UTC, PandaRec commented on app/src/main/java/com/example/designfromfigma2/ui/home/HomeFragment.kt
> +
cделал

2021-04-23 11:08 UTC, PandaRec commented on app/src/main/res/layout/fragment_home.xml
> +        android:queryHint="Search"
сделал

2021-04-23 11:08 UTC, PandaRec commented on app/src/main/res/layout/fragment_home.xml
> +    <ImageView
cделал

2021-04-30 22:19 UTC, merged