Cart
PandaRec/DesignFromFigma pull request #7
Opened 2021-05-06 15:16 UTC by PandaRec

2021-05-06 17:20 UTC, sbalakin requested changes

2021-05-06 17:20 UTC, sbalakin commented on app/src/main/java/com/example/designfromfigma2/adapters/CartAdapter.kt
> +    var onPlusClickListener:OnPlusClickListener?=null
через ClickListener  не делают, используют BehaviorSubject

2021-05-07 10:42 UTC, PandaRec commented on app/src/main/java/com/example/designfromfigma2/adapters/CartAdapter.kt
> +    var onPlusClickListener:OnPlusClickListener?=null
сделал

2021-05-07 11:10 UTC, sbalakin approved these changes

2021-05-07 15:17 UTC, merged